spring:
  redis:
    database: 0
    host: 192.168.181.133
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000
  data:
    mongodb:
      uri: mongodb://admin:admin@120.27.225.59:27017/testdb

server:
  port: 80
